// Code generated by counterfeiter. DO NOT EDIT.
package authfakes

import (
	"net/http"
	"sync"

	"github.com/concourse/atc/api/auth"
)

type FakeTokenValidator struct {
	IsAuthenticatedStub        func(r *http.Request) bool
	isAuthenticatedMutex       sync.RWMutex
	isAuthenticatedArgsForCall []struct {
		r *http.Request
	}
	isAuthenticatedReturns struct {
		result1 bool
	}
	isAuthenticatedReturnsOnCall map[int]struct {
		result1 bool
	}
	GetUserIdStub        func(r *http.Request) (string, bool)
	getUserIdMutex       sync.RWMutex
	getUserIdArgsForCall []struct {
		r *http.Request
	}
	getUserIdReturns struct {
		result1 string
		result2 bool
	}
	getUserIdReturnsOnCall map[int]struct {
		result1 string
		result2 bool
	}
	GetTeamsStub        func(r *http.Request) ([]string, bool, bool)
	getTeamsMutex       sync.RWMutex
	getTeamsArgsForCall []struct {
		r *http.Request
	}
	getTeamsReturns struct {
		result1 []string
		result2 bool
		result3 bool
	}
	getTeamsReturnsOnCall map[int]struct {
		result1 []string
		result2 bool
		result3 bool
	}
	GetSystemStub        func(r *http.Request) (bool, bool)
	getSystemMutex       sync.RWMutex
	getSystemArgsForCall []struct {
		r *http.Request
	}
	getSystemReturns struct {
		result1 bool
		result2 bool
	}
	getSystemReturnsOnCall map[int]struct {
		result1 bool
		result2 bool
	}
	GetCSRFTokenStub        func(r *http.Request) (string, bool)
	getCSRFTokenMutex       sync.RWMutex
	getCSRFTokenArgsForCall []struct {
		r *http.Request
	}
	getCSRFTokenReturns struct {
		result1 string
		result2 bool
	}
	getCSRFTokenReturnsOnCall map[int]struct {
		result1 string
		result2 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokenValidator) IsAuthenticated(r *http.Request) bool {
	fake.isAuthenticatedMutex.Lock()
	ret, specificReturn := fake.isAuthenticatedReturnsOnCall[len(fake.isAuthenticatedArgsForCall)]
	fake.isAuthenticatedArgsForCall = append(fake.isAuthenticatedArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("IsAuthenticated", []interface{}{r})
	fake.isAuthenticatedMutex.Unlock()
	if fake.IsAuthenticatedStub != nil {
		return fake.IsAuthenticatedStub(r)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.isAuthenticatedReturns.result1
}

func (fake *FakeTokenValidator) IsAuthenticatedCallCount() int {
	fake.isAuthenticatedMutex.RLock()
	defer fake.isAuthenticatedMutex.RUnlock()
	return len(fake.isAuthenticatedArgsForCall)
}

func (fake *FakeTokenValidator) IsAuthenticatedArgsForCall(i int) *http.Request {
	fake.isAuthenticatedMutex.RLock()
	defer fake.isAuthenticatedMutex.RUnlock()
	return fake.isAuthenticatedArgsForCall[i].r
}

func (fake *FakeTokenValidator) IsAuthenticatedReturns(result1 bool) {
	fake.IsAuthenticatedStub = nil
	fake.isAuthenticatedReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeTokenValidator) IsAuthenticatedReturnsOnCall(i int, result1 bool) {
	fake.IsAuthenticatedStub = nil
	if fake.isAuthenticatedReturnsOnCall == nil {
		fake.isAuthenticatedReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.isAuthenticatedReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakeTokenValidator) GetUserId(r *http.Request) (string, bool) {
	fake.getUserIdMutex.Lock()
	ret, specificReturn := fake.getUserIdReturnsOnCall[len(fake.getUserIdArgsForCall)]
	fake.getUserIdArgsForCall = append(fake.getUserIdArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("GetUserId", []interface{}{r})
	fake.getUserIdMutex.Unlock()
	if fake.GetUserIdStub != nil {
		return fake.GetUserIdStub(r)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getUserIdReturns.result1, fake.getUserIdReturns.result2
}

func (fake *FakeTokenValidator) GetUserIdCallCount() int {
	fake.getUserIdMutex.RLock()
	defer fake.getUserIdMutex.RUnlock()
	return len(fake.getUserIdArgsForCall)
}

func (fake *FakeTokenValidator) GetUserIdArgsForCall(i int) *http.Request {
	fake.getUserIdMutex.RLock()
	defer fake.getUserIdMutex.RUnlock()
	return fake.getUserIdArgsForCall[i].r
}

func (fake *FakeTokenValidator) GetUserIdReturns(result1 string, result2 bool) {
	fake.GetUserIdStub = nil
	fake.getUserIdReturns = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeTokenValidator) GetUserIdReturnsOnCall(i int, result1 string, result2 bool) {
	fake.GetUserIdStub = nil
	if fake.getUserIdReturnsOnCall == nil {
		fake.getUserIdReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
		})
	}
	fake.getUserIdReturnsOnCall[i] = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeTokenValidator) GetTeams(r *http.Request) ([]string, bool, bool) {
	fake.getTeamsMutex.Lock()
	ret, specificReturn := fake.getTeamsReturnsOnCall[len(fake.getTeamsArgsForCall)]
	fake.getTeamsArgsForCall = append(fake.getTeamsArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("GetTeams", []interface{}{r})
	fake.getTeamsMutex.Unlock()
	if fake.GetTeamsStub != nil {
		return fake.GetTeamsStub(r)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.getTeamsReturns.result1, fake.getTeamsReturns.result2, fake.getTeamsReturns.result3
}

func (fake *FakeTokenValidator) GetTeamsCallCount() int {
	fake.getTeamsMutex.RLock()
	defer fake.getTeamsMutex.RUnlock()
	return len(fake.getTeamsArgsForCall)
}

func (fake *FakeTokenValidator) GetTeamsArgsForCall(i int) *http.Request {
	fake.getTeamsMutex.RLock()
	defer fake.getTeamsMutex.RUnlock()
	return fake.getTeamsArgsForCall[i].r
}

func (fake *FakeTokenValidator) GetTeamsReturns(result1 []string, result2 bool, result3 bool) {
	fake.GetTeamsStub = nil
	fake.getTeamsReturns = struct {
		result1 []string
		result2 bool
		result3 bool
	}{result1, result2, result3}
}

func (fake *FakeTokenValidator) GetTeamsReturnsOnCall(i int, result1 []string, result2 bool, result3 bool) {
	fake.GetTeamsStub = nil
	if fake.getTeamsReturnsOnCall == nil {
		fake.getTeamsReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 bool
			result3 bool
		})
	}
	fake.getTeamsReturnsOnCall[i] = struct {
		result1 []string
		result2 bool
		result3 bool
	}{result1, result2, result3}
}

func (fake *FakeTokenValidator) GetSystem(r *http.Request) (bool, bool) {
	fake.getSystemMutex.Lock()
	ret, specificReturn := fake.getSystemReturnsOnCall[len(fake.getSystemArgsForCall)]
	fake.getSystemArgsForCall = append(fake.getSystemArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("GetSystem", []interface{}{r})
	fake.getSystemMutex.Unlock()
	if fake.GetSystemStub != nil {
		return fake.GetSystemStub(r)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getSystemReturns.result1, fake.getSystemReturns.result2
}

func (fake *FakeTokenValidator) GetSystemCallCount() int {
	fake.getSystemMutex.RLock()
	defer fake.getSystemMutex.RUnlock()
	return len(fake.getSystemArgsForCall)
}

func (fake *FakeTokenValidator) GetSystemArgsForCall(i int) *http.Request {
	fake.getSystemMutex.RLock()
	defer fake.getSystemMutex.RUnlock()
	return fake.getSystemArgsForCall[i].r
}

func (fake *FakeTokenValidator) GetSystemReturns(result1 bool, result2 bool) {
	fake.GetSystemStub = nil
	fake.getSystemReturns = struct {
		result1 bool
		result2 bool
	}{result1, result2}
}

func (fake *FakeTokenValidator) GetSystemReturnsOnCall(i int, result1 bool, result2 bool) {
	fake.GetSystemStub = nil
	if fake.getSystemReturnsOnCall == nil {
		fake.getSystemReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 bool
		})
	}
	fake.getSystemReturnsOnCall[i] = struct {
		result1 bool
		result2 bool
	}{result1, result2}
}

func (fake *FakeTokenValidator) GetCSRFToken(r *http.Request) (string, bool) {
	fake.getCSRFTokenMutex.Lock()
	ret, specificReturn := fake.getCSRFTokenReturnsOnCall[len(fake.getCSRFTokenArgsForCall)]
	fake.getCSRFTokenArgsForCall = append(fake.getCSRFTokenArgsForCall, struct {
		r *http.Request
	}{r})
	fake.recordInvocation("GetCSRFToken", []interface{}{r})
	fake.getCSRFTokenMutex.Unlock()
	if fake.GetCSRFTokenStub != nil {
		return fake.GetCSRFTokenStub(r)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getCSRFTokenReturns.result1, fake.getCSRFTokenReturns.result2
}

func (fake *FakeTokenValidator) GetCSRFTokenCallCount() int {
	fake.getCSRFTokenMutex.RLock()
	defer fake.getCSRFTokenMutex.RUnlock()
	return len(fake.getCSRFTokenArgsForCall)
}

func (fake *FakeTokenValidator) GetCSRFTokenArgsForCall(i int) *http.Request {
	fake.getCSRFTokenMutex.RLock()
	defer fake.getCSRFTokenMutex.RUnlock()
	return fake.getCSRFTokenArgsForCall[i].r
}

func (fake *FakeTokenValidator) GetCSRFTokenReturns(result1 string, result2 bool) {
	fake.GetCSRFTokenStub = nil
	fake.getCSRFTokenReturns = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeTokenValidator) GetCSRFTokenReturnsOnCall(i int, result1 string, result2 bool) {
	fake.GetCSRFTokenStub = nil
	if fake.getCSRFTokenReturnsOnCall == nil {
		fake.getCSRFTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 bool
		})
	}
	fake.getCSRFTokenReturnsOnCall[i] = struct {
		result1 string
		result2 bool
	}{result1, result2}
}

func (fake *FakeTokenValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isAuthenticatedMutex.RLock()
	defer fake.isAuthenticatedMutex.RUnlock()
	fake.getUserIdMutex.RLock()
	defer fake.getUserIdMutex.RUnlock()
	fake.getTeamsMutex.RLock()
	defer fake.getTeamsMutex.RUnlock()
	fake.getSystemMutex.RLock()
	defer fake.getSystemMutex.RUnlock()
	fake.getCSRFTokenMutex.RLock()
	defer fake.getCSRFTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokenValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ auth.TokenValidator = new(FakeTokenValidator)
